[tools]
elixir = "1.19.5-otp-28"
elixir-ls = "latest"
erlang = "28.1"
go = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "latest"
"npm:typescript" = "latest"
pnpm = "latest"
python = "3"
rust = { version = "latest", components = "rust-src,rust-analyzer,rustfmt" }
shfmt = "latest"
stylua = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
terrascan = "latest"
tflint = "latest"
uv = "latest"
